# springcloud-config
# ssh-keygen -t ecdsa -b 521 -C "taoy9527@gmail.com"
# ssh-keygen -t ed25519 -C "taoy9527@gmail.com"
# git remote add origin git@github.com:AlwaysBeKindT/springcloud-config.git
cofig:
	info: "master branch,springcloud-config/config-dev.yml version=1"